[display]
show_line_numbers = true
show_relative_numbers = false
show_cursor_line = false
color_scheme = "default"
syntax_highlighting = true

[behavior]
tab_width = 4
expand_tabs = false
auto_indent = true
ignore_case = false
smart_case = false
highlight_search = true
incremental_search = true
wrap_lines = false
line_break = false

[editing]
undo_levels = 1000
persistent_undo = false
backup = false
swap_file = false
auto_save = false

[interface]
show_status_line = true
status_line_format = "default"
command_timeout = 1000
show_command = true
scroll_off = 0
side_scroll_off = 0
