# Syntax Highlighting Configuration
# This file defines language grammars and color themes for syntax highlighting

[general]
enabled = true
default_theme = "default"

# Language definitions
[languages.rust]
name = "Rust"
extensions = ["rs"]
grammar = "rust"
comment_token = "//"

# Default color theme - Rust Inspired
[themes.default]
# Basic syntax elements - Rust language colors
keyword = { fg = "#ce422b", bold = true }        # Rust red/orange - core language keywords
string = { fg = "#b4a72e", italic = true }       # Golden yellow - string literals  
comment = { fg = "#5c6773", italic = true }      # Muted gray - comments
number = { fg = "#ff9940", bold = true }         # Bright orange - numeric literals
boolean = { fg = "#ce422b" }                     # Rust red - boolean values
operator = { fg = "#ff6a00" }                    # Bright rust orange - operators
punctuation = { fg = "#dbd7ca" }                 # Light cream - punctuation

# Language constructs - Safety and performance themed
function = { fg = "#39adb5", bold = true }       # Teal blue - functions (reliability)
type = { fg = "#86b300", bold = true }           # Fresh green - types (safety)
variable = { fg = "#dbd7ca" }                    # Light cream - variables
constant = { fg = "#f29718", bold = true }       # Vibrant orange - constants
property = { fg = "#59c2ff" }                    # Sky blue - properties/fields

# Special elements - Error handling and memory safety
escape = { fg = "#f29718" }                      # Orange - escape sequences
error = { fg = "#ff3333", bold = true }          # Bright red - errors
warning = { fg = "#ff9940" }                     # Orange - warnings

# Markdown specific - Documentation colors
heading = { fg = "#ce422b", bold = true }        # Rust red - headings
emphasis = { fg = "#b4a72e", italic = true }     # Golden - emphasis
strong = { fg = "#86b300", bold = true }         # Green - strong text
code = { fg = "#39adb5" }                        # Teal - code blocks
link = { fg = "#59c2ff", underline = true }      # Sky blue - links

# Alternative themes
[themes.dark]
keyword = { fg = "#ff6b35", bold = true }        # Bright rust orange
string = { fg = "#ffd23f", italic = true }       # Bright golden yellow
comment = { fg = "#7c7c7c", italic = true }      # Medium gray
function = { fg = "#00d4aa", bold = true }       # Bright teal
type = { fg = "#a3d977", bold = true }           # Bright green

[themes.light]
keyword = { fg = "#b7410e", bold = true }        # Dark rust red
string = { fg = "#8b6914", italic = true }       # Dark golden
comment = { fg = "#8e8e93", italic = true }      # Light gray
function = { fg = "#007acc", bold = true }       # Deep blue
type = { fg = "#22863a", bold = true }           # Forest green

# Rust ferris theme - inspired by the Rust mascot
[themes.ferris]
keyword = { fg = "#ce422b", bold = true }        # Classic Rust red
string = { fg = "#f1c40f" }                      # Ferris yellow
comment = { fg = "#95a5a6", italic = true }      # Silver gray
function = { fg = "#e67e22", bold = true }       # Orange
type = { fg = "#27ae60", bold = true }           # Emerald green
variable = { fg = "#ecf0f1" }                    # Almost white
number = { fg = "#f39c12" }                      # Bright orange
boolean = { fg = "#e74c3c" }                     # Red
operator = { fg = "#ff9500" }                    # Rust orange
punctuation = { fg = "#bdc3c7" }                 # Light gray
