# Comprehensive theme configuration for UI and Syntax highlighting
# This file supports hot reloading - changes take effect immediately

[theme]
# Current active theme: "dark"
current = "dark"

# Dark theme for low-light environments
[themes.dark]
name = "Rust Dark"
description = "High contrast dark theme for late-night coding"

[themes.dark.ui]
background = "#0d1117"          # Very dark background
status_bg = "#a3d977"           # Bright green
status_fg = "#282828"           # Dark text for contrast
status_modified = "#ff6b35"     # Bright rust orange
line_number = "#7c7c7c"         # Medium gray
line_number_current = "#ffd23f" # Bright golden
cursor_line_bg = "#373737"      # Darker background
empty_line = "#00d4aa"          # Bright teal
command_line_bg = "#191919"     # Very dark background
command_line_fg = "#ffffff"     # White text
selection_bg = "#a3d977"        # Match status bg
warning = "#ffd23f"             # Bright golden
error = "#ff6b35"               # Bright rust orange

[themes.dark.syntax]
text = "#cccccc"      # Pure white text
comment = "#7c7c7c"   # Medium gray
keyword = "#ff6b35"   # Bright rust orange
operator = "#ffd23f"  # Bright golden
type = "#a3d977"      # Bright green
struct = "#a3d977"    # Bright green
enum = "#a3d977"      # Bright green
string = "#98d982"    # Bright light green
number = "#ffb347"    # Bright golden orange
boolean = "#00d4aa"   # Bright teal
character = "#98d982" # Bright light green
function = "#00d4aa"  # Bright teal
method = "#00d4aa"    # Bright teal
macro = "#e879f9"     # Bright purple
variable = "#ff69b4"  # Hot Pink - very visible change 
parameter = "#ff9999" # Bright soft red
property = "#87ceeb"  # Bright sky blue
constant = "#ffd23f"  # Bright golden
